ARG ENVOY_VERSION
FROM envoyproxy/envoy:v1.20-latest

RUN apt-get update && apt-get -q install -y \
    gdbserver \
    tcpdump \
    nmap \
    curl
CMD /usr/local/bin/envoy -c /etc/envoy.yaml -l debug
