ARG ENVOY_VERSION
FROM rodeeend/envoy-devel:${ENVOY_VERSION:-latest}

RUN apt-get update && apt-get -q install -y \
    gdbserver \
    tcpdump \
    nmap \
    curl
CMD /usr/local/bin/envoy -c /etc/envoy.yaml -l debug
